### ISSUE TITLE
Missing modules?

### ISSUE THREAD

**Issue by CAReeser** [tudo-astroparticlephysics/all_sky_cloud_detection#11]
in star_selection.py there are two imports:

- from _all_sky_cloud_detection.coordinate_transformation import pixel2horizontal
- from_ all_sky_cloud_detection.preparation import normalize_image

I cannot locate all_sky_cloud_detection.coordinate_transformation
I cannot locate all_sky_cloud_detection.preparation
So these imports fail.

Are these missing modules or part of another import?
Thanks.
Cliff

**Comment by CAReeser** [comment]
Never mind, I found your latest version.
Thx

**Comment by LuisGoncalves1** [comment]
Hello, sorry for bothering.
I came into the same problem, but i can't seem to find the latest version, where is it?
Also, does the code still work?
Thanks,
Luís

**Comment by CAReeser** [comment]
Luis,
The version is old and needs a lot of rewriting.  Many of the functions required extensive manual installation and setup to be useful on other than the original sites.  

We are developing a product that was going to use some of this code, but we spent $75k completely rewriting it and more on productizing it.  If you need a product like this, we are entering alpha test phase tomorrow. We are lining up beta sites if you have a need.

Our product, The TychoCam has a web interface, administrative functions such as user login requesting and tracking, system alerting, auto scheduling of tasks, image downloads, POE, images assembled into movies, and has an integrated Alpaca API for monitoring cloud coverage and local atmospheric conditions from client Alpaca compatible telescope/dome/etc software.  

Let me know if you are interested.

Cliff
cliff.reeser@tychodesign.net
512-575-0064
