### ISSUE TITLE
Provide catalogs and files used in the examples

### ISSUE THREAD

**Issue by irasnyd** [tudo-astroparticlephysics/all_sky_cloud_detection#6]
This code relies on catalogs (`hipparcos_catalog.csv`, etc.) and FITS files which are not available in this source repository.

It would be very helpful for users and potential contributors if these resources were provided either in this source repository directly, or as links in the README.

**Comment by HelenaChiara** [comment]
Thanks for the advice! The catalog and two sample images are now available. 
The images are stored in `tests/resources/iceact_images ` and can be processed with `process_iceact.py`. The catalog is located in `all_sky_cloud_detection/resources/hipparcos.fits.gz`.
